// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Urql from "urql";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_array from "bs-platform/lib/es6/caml_array.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as UrqlCombinedError from "../utils/UrqlCombinedError.bs.js";

function useSubscriptionResponseToRecord(parse, result) {
  var data = Belt_Option.map(Caml_option.nullable_to_opt(result.data), parse);
  var error = Belt_Option.map(Caml_option.undefined_to_opt(result.error), UrqlCombinedError.combinedErrorToRecord);
  var fetching = result.fetching;
  var response = fetching ? (
      data !== undefined ? /* Data */Block.__(0, [Caml_option.valFromOption(data)]) : /* Fetching */0
    ) : (
      error !== undefined ? /* Error */Block.__(1, [error]) : (
          data !== undefined ? /* Data */Block.__(0, [Caml_option.valFromOption(data)]) : /* NotFound */1
        )
    );
  return /* record */[
          /* fetching */fetching,
          /* data */data,
          /* error */error,
          /* response */response
        ];
}

function useSubscription(request, handler) {
  var parse = request.parse;
  var args = {
    query: request.query,
    variables: request.variables
  };
  return React.useMemo((function () {
                if (handler) {
                  var handlerFn = handler[0];
                  return useSubscriptionResponseToRecord((function (x) {
                                return x;
                              }), Caml_array.caml_array_get(Urql.useSubscription(args, (function (acc, data) {
                                        return Curry._2(handlerFn, acc, Curry._1(parse, data));
                                      })), 0));
                } else {
                  return useSubscriptionResponseToRecord(parse, Caml_array.caml_array_get(Urql.useSubscription(args, undefined), 0));
                }
              }), /* tuple */[
              handler,
              args,
              parse
            ]);
}

export {
  useSubscription ,
  
}
/* urql Not a pure module */
