// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Urql from "urql";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as UrqlTypes from "../UrqlTypes.bs.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as UrqlCombinedError from "../utils/UrqlCombinedError.bs.js";

var QueryJs = { };

function urqlQueryResponseToReason(parse, result) {
  var data = Belt_Option.map(Caml_option.nullable_to_opt(result.data), parse);
  var error = Belt_Option.map(Caml_option.nullable_to_opt(result.error), UrqlCombinedError.combinedErrorToRecord);
  var fetching = result.fetching;
  var executeQuery = result.executeQuery;
  var response = fetching ? /* Fetching */0 : (
      error !== undefined ? /* Error */Block.__(1, [error]) : (
          data !== undefined ? /* Data */Block.__(0, [Caml_option.valFromOption(data)]) : /* NotFound */1
        )
    );
  return /* record */[
          /* fetching */fetching,
          /* data */data,
          /* error */error,
          /* executeQuery */executeQuery,
          /* response */response
        ];
}

function UrqlQuery(Props) {
  var request = Props.request;
  var match = Props.requestPolicy;
  var requestPolicy = match !== undefined ? match : /* CacheFirst */973529774;
  var pause = Props.pause;
  var children = Props.children;
  var query = request.query;
  var variables = request.variables;
  var parse = request.parse;
  var tmp = {
    query: query,
    variables: variables,
    requestPolicy: UrqlTypes.requestPolicyToJs(requestPolicy),
    children: (function (result) {
        return Curry._1(children, urqlQueryResponseToReason(parse, result));
      })
  };
  if (pause !== undefined) {
    tmp.pause = Caml_option.valFromOption(pause);
  }
  return React.createElement(Urql.Query, tmp);
}

var make = UrqlQuery;

export {
  QueryJs ,
  urqlQueryResponseToReason ,
  make ,
  
}
/* urql Not a pure module */
