// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Urql from "urql";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as UrqlCombinedError from "../utils/UrqlCombinedError.bs.js";

var MutationJs = { };

function urqlMutationResponseToReason(parse, variables, result) {
  var data = Belt_Option.map(Caml_option.nullable_to_opt(result.data), parse);
  var error = Belt_Option.map(Caml_option.nullable_to_opt(result.error), UrqlCombinedError.combinedErrorToRecord);
  var fetching = result.fetching;
  var executeMutationFn = result.executeMutation;
  var executeMutation = function (param) {
    return Curry._1(executeMutationFn, Caml_option.some(variables));
  };
  var response = fetching ? /* Fetching */0 : (
      error !== undefined ? /* Error */Block.__(1, [error]) : (
          data !== undefined ? /* Data */Block.__(0, [Caml_option.valFromOption(data)]) : /* NotFound */1
        )
    );
  return /* record */[
          /* fetching */fetching,
          /* data */data,
          /* error */error,
          /* executeMutation */executeMutation,
          /* response */response
        ];
}

function UrqlMutation(Props) {
  var request = Props.request;
  var children = Props.children;
  var query = request.query;
  var variables = request.variables;
  var parse = request.parse;
  return React.createElement(Urql.Mutation, {
              query: query,
              children: (function (result) {
                  return Curry._1(children, urqlMutationResponseToReason(parse, variables, result));
                })
            });
}

var make = UrqlMutation;

export {
  MutationJs ,
  urqlMutationResponseToReason ,
  make ,
  
}
/* urql Not a pure module */
