// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Urql from "urql";
import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as UrqlCombinedError from "../utils/UrqlCombinedError.bs.js";

var SubscriptionJs = { };

function urqlDataToRecord(parse, result) {
  var data = Belt_Option.map(Caml_option.nullable_to_opt(result.data), parse);
  var error = Belt_Option.map(Caml_option.undefined_to_opt(result.error), UrqlCombinedError.combinedErrorToRecord);
  var fetching = result.fetching;
  var response = fetching ? (
      data !== undefined ? /* Data */Block.__(0, [Caml_option.valFromOption(data)]) : /* Fetching */0
    ) : (
      error !== undefined ? /* Error */Block.__(1, [error]) : (
          data !== undefined ? /* Data */Block.__(0, [Caml_option.valFromOption(data)]) : /* NotFound */1
        )
    );
  return /* record */[
          /* fetching */fetching,
          /* data */data,
          /* error */error,
          /* response */response
        ];
}

function UrqlSubscription$Subscription(Props) {
  var request = Props.request;
  var children = Props.children;
  var query = request.query;
  var variables = request.variables;
  var parse = request.parse;
  return React.createElement(Urql.Subscription, {
              query: query,
              variables: variables,
              children: (function (result) {
                  return Curry._1(children, urqlDataToRecord(parse, result));
                })
            });
}

var Subscription = {
  make: UrqlSubscription$Subscription
};

function UrqlSubscription$SubscriptionWithHandler(Props) {
  var request = Props.request;
  var handler = Props.handler;
  var children = Props.children;
  var query = request.query;
  var variables = request.variables;
  var parse = request.parse;
  var applyParsedResponse = function (acc, data) {
    return Curry._2(handler, acc, Curry._1(parse, data));
  };
  return React.createElement(Urql.Subscription, {
              query: query,
              variables: variables,
              handler: applyParsedResponse,
              children: (function (result) {
                  return Curry._1(children, urqlDataToRecord((function (x) {
                                    return x;
                                  }), result));
                })
            });
}

var SubscriptionWithHandler = {
  make: UrqlSubscription$SubscriptionWithHandler
};

export {
  SubscriptionJs ,
  urqlDataToRecord ,
  Subscription ,
  SubscriptionWithHandler ,
  
}
/* urql Not a pure module */
