// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";
import * as React from "react";
import * as Messages from "./Messages.bs.js";
import * as AppStyles from "./AppStyles.bs.js";
import * as MessagesHooks from "./MessagesHooks.bs.js";

function App(Props) {
  return React.createElement("div", {
              className: Css.style(/* :: */[
                    Css.display(/* grid */-999565626),
                    /* :: */[
                      Css.gridTemplateColumns(/* :: */[
                            /* `repeat */[
                              108828507,
                              /* tuple */[
                                /* `num */[
                                  5496390,
                                  2
                                ],
                                /* `fr */[
                                  22860,
                                  1
                                ]
                              ]
                            ],
                            /* [] */0
                          ]),
                      /* :: */[
                        Css.gridGap(Css.px(10)),
                        /* [] */0
                      ]
                    ]
                  ])
            }, React.createElement("div", undefined, React.createElement("h1", {
                      className: AppStyles.Styles.dexText
                    }, "src/Messages.Re"), React.createElement(Messages.make, { })), React.createElement("div", undefined, React.createElement("h1", {
                      className: AppStyles.Styles.dexText
                    }, "src/MessagesHooks.Re"), React.createElement(MessagesHooks.make, { })));
}

var make = App;

export {
  make ,
  
}
/* Css Not a pure module */
