// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Messages from "./Messages.bs.js";
import * as AppStyles from "./AppStyles.bs.js";

function App(Props) {
  return React.createElement("div", {
              className: AppStyles.page
            }, React.createElement(Messages.make, { }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
