// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var page = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.alignItems(Css.center),
          /* :: */[
            Css.justifyContent(Css.center),
            /* :: */[
              Css.position(Css.absolute),
              /* :: */[
                Css.top(Css.px(0)),
                /* :: */[
                  Css.bottom(Css.px(0)),
                  /* :: */[
                    Css.left(Css.px(0)),
                    /* :: */[
                      Css.right(Css.px(0)),
                      /* :: */[
                        Css.padding(Css.px(20)),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

export {
  page ,
  
}
/* page Not a pure module */
