// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE


function decodeResponse(data) {
  var id = data.newMessage.id;
  var message = data.newMessage.message;
  return /* record */[/* newMessage : record */[
            /* id */id,
            /* message */message
          ]];
}

export {
  decodeResponse ,
  
}
/* No side effect */
