// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as $$String from "bs-platform/lib/es6/string.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function HandleError(Props) {
  var e = Props.e;
  var match = e[/* networkError */0];
  if (match !== undefined) {
    return React.createElement("div", undefined, Belt_Option.getWithDefault(Caml_option.valFromOption(match).message, "Network error"));
  } else {
    var match$1 = e[/* graphQLErrors */1];
    if (match$1 !== undefined) {
      return React.createElement("div", undefined, $$String.concat(", ", List.map((function (e) {
                            var msg = Belt_Option.getWithDefault(Caml_option.nullable_to_opt(e.message), "GraphQL error");
                            return "[GraphQLError: " + (msg + "]");
                          }), $$Array.to_list(match$1))));
    } else {
      return React.createElement("div", undefined, "Unknown error.");
    }
  }
}

var make = HandleError;

export {
  make ,
  
}
/* react Not a pure module */
