// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Array from "bs-platform/lib/es6/array.js";
import * as React from "react";
import * as Decode from "./Decode.bs.js";
import * as Js_exn from "bs-platform/lib/es6/js_exn.js";
import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Js_json from "bs-platform/lib/es6/js_json.js";
import * as Js_option from "bs-platform/lib/es6/js_option.js";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as UrqlSubscription from "./reason-urql/components/UrqlSubscription.bs.js";

var ppx_printed_query = "subscription subscribeMessage  {\nnewMessage  {\nid  \nmessage  \n}\n\n}\n";

function parse(value) {
  var value$1 = Js_option.getExn(Js_json.decodeObject(value));
  var match = Js_dict.get(value$1, "newMessage");
  var tmp;
  if (match !== undefined) {
    var value$2 = Js_option.getExn(Js_json.decodeObject(Caml_option.valFromOption(match)));
    var match$1 = Js_dict.get(value$2, "id");
    var tmp$1;
    if (match$1 !== undefined) {
      var value$3 = Caml_option.valFromOption(match$1);
      var match$2 = Js_json.decodeString(value$3);
      tmp$1 = match$2 !== undefined ? match$2 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$3));
    } else {
      tmp$1 = Js_exn.raiseError("graphql_ppx: Field id on type Message is missing");
    }
    var match$3 = Js_dict.get(value$2, "message");
    var tmp$2;
    if (match$3 !== undefined) {
      var value$4 = Caml_option.valFromOption(match$3);
      var match$4 = Js_json.decodeString(value$4);
      tmp$2 = match$4 !== undefined ? match$4 : Js_exn.raiseError("graphql_ppx: Expected string, got " + JSON.stringify(value$4));
    } else {
      tmp$2 = Js_exn.raiseError("graphql_ppx: Field message on type Message is missing");
    }
    tmp = {
      id: tmp$1,
      message: tmp$2
    };
  } else {
    tmp = Js_exn.raiseError("graphql_ppx: Field newMessage on type Subscription is missing");
  }
  return {
          newMessage: tmp
        };
}

function make(param) {
  return {
          query: ppx_printed_query,
          variables: null,
          parse: parse
        };
}

function makeWithVariables(param) {
  return {
          query: ppx_printed_query,
          variables: null,
          parse: parse
        };
}

function makeVariables(param) {
  return null;
}

function definition_002(graphql_ppx_use_json_variables_fn) {
  return 0;
}

var definition = /* tuple */[
  parse,
  ppx_printed_query,
  definition_002
];

function ret_type(f) {
  return { };
}

var MT_Ret = { };

var SubscribeNewMessage = {
  ppx_printed_query: ppx_printed_query,
  query: ppx_printed_query,
  parse: parse,
  make: make,
  makeWithVariables: makeWithVariables,
  makeVariables: makeVariables,
  definition: definition,
  ret_type: ret_type,
  MT_Ret: MT_Ret
};

function handler(prevSubscriptions, subscription) {
  if (prevSubscriptions !== undefined) {
    return $$Array.append(prevSubscriptions, /* array */[subscription]);
  } else {
    return /* array */[subscription];
  }
}

function getRandomInt(max) {
  return Math.floor(Math.random() * max);
}

function getRandomHex(param) {
  var encode = Math.floor(Math.random() * 16777215);
  var hex = encode.toString(16);
  return "#" + (String(hex) + "");
}

var request = make(/* () */0);

function Messages(Props) {
  return React.createElement(UrqlSubscription.SubscriptionWithHandler.make, {
              request: request,
              handler: handler,
              children: (function (param) {
                  var response = param[/* response */3];
                  if (typeof response === "number") {
                    if (response === /* Fetching */0) {
                      return React.createElement("text", undefined, "Loading");
                    } else {
                      return React.createElement("text", undefined, "Not Found");
                    }
                  } else if (response.tag) {
                    return React.createElement("text", undefined, "Error");
                  } else {
                    var newMessages = Belt_Array.keepMap(response[0], (function (item) {
                            return Caml_option.some(item);
                          }));
                    var messages = Belt_Array.map(newMessages, Decode.decodeResponse);
                    Belt_Array.map(messages, (function (m) {
                            console.log(m[/* newMessage */0]);
                            return /* () */0;
                          }));
                    return React.createElement("text", undefined, "Error");
                  }
                })
            });
}

var make$1 = Messages;

export {
  SubscribeNewMessage ,
  handler ,
  getRandomInt ,
  getRandomHex ,
  request ,
  make$1 as make,
  
}
/* request Not a pure module */
