// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var dexContainer = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.alignItems(Css.flexStart),
        /* :: */[
          Css.justifyContent(Css.center),
          /* :: */[
            Css.margin(Css.auto),
            /* :: */[
              Css.width(Css.rem(25)),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

var dex = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.width(Css.pct(100)),
          /* :: */[
            Css.borderRadius(Css.pct(5)),
            /* :: */[
              Css.overflow(Css.hidden),
              /* :: */[
                Css.alignItems(Css.center),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var dexImageContainer = Css.style(/* :: */[
      Css.overflow(Css.hidden),
      /* :: */[
        Css.display(Css.flexBox),
        /* :: */[
          Css.justifyContent(Css.center),
          /* :: */[
            Css.alignItems(Css.center),
            /* :: */[
              Css.width(Css.rem(12)),
              /* :: */[
                Css.height(Css.rem(12)),
                /* :: */[
                  Css.borderRadius(Css.pct(100)),
                  /* :: */[
                    Css.backgroundColor(Css.white),
                    /* :: */[
                      Css.border(Css.px(2), Css.solid, Css.black),
                      /* :: */[
                        Css.margin(Css.rem(2)),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var dexImage = Css.style(/* :: */[
      Css.height(Css.rem(8)),
      /* [] */0
    ]);

var dexText = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.backgroundColor(Css.white),
          /* :: */[
            Css.width(Css.pct(100)),
            /* :: */[
              Css.borderBottomLeftRadius(Css.pct(5.0)),
              /* :: */[
                Css.borderBottomRightRadius(Css.pct(5.0)),
                /* :: */[
                  Css.alignItems(Css.center),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var dexTitle = Css.style(/* :: */[
      Css.fontSize(Css.rem(2)),
      /* :: */[
        Css.margin(Css.zero),
        /* :: */[
          Css.padding(Css.rem(0.5)),
          /* [] */0
        ]
      ]
    ]);

var dexSubTitle = Css.style(/* :: */[
      Css.fontSize(Css.rem(1.5)),
      /* :: */[
        Css.margin(Css.zero),
        /* :: */[
          Css.padding(Css.rem(0.25)),
          /* [] */0
        ]
      ]
    ]);

var dexGrid = Css.style(/* :: */[
      Css.display(Css.grid),
      /* :: */[
        Css.gridTemplateColumns(/* :: */[
              /* `fr */[
                22860,
                1
              ],
              /* :: */[
                /* `fr */[
                  22860,
                  1
                ],
                /* [] */0
              ]
            ]),
        /* [] */0
      ]
    ]);

var Styles = {
  dexContainer: dexContainer,
  dex: dex,
  dexImageContainer: dexImageContainer,
  dexImage: dexImage,
  dexText: dexText,
  dexTitle: dexTitle,
  dexSubTitle: dexSubTitle,
  dexGrid: dexGrid
};

export {
  Styles ,
  
}
/* dexContainer Not a pure module */
