// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function combinedErrorToRecord(err) {
  return /* record */[
          /* networkError */Caml_option.nullable_to_opt(err.networkError),
          /* graphQLErrors */Caml_option.nullable_to_opt(err.graphQLErrors),
          /* response */Caml_option.nullable_to_opt(err.response),
          /* message */err.message
        ];
}

export {
  combinedErrorToRecord ,
  
}
/* No side effect */
