// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as UrqlClient from "./UrqlClient.bs.js";
import * as UrqlUseQuery from "./hooks/UrqlUseQuery.bs.js";
import * as UrqlUseMutation from "./hooks/UrqlUseMutation.bs.js";
import * as UrqlUseSubscription from "./hooks/UrqlUseSubscription.bs.js";

var Client = {
  unwrapFetchOptions: UrqlClient.unwrapFetchOptions,
  ClientTypes: UrqlClient.ClientTypes,
  UrqlExchanges: UrqlClient.UrqlExchanges,
  make: UrqlClient.make,
  urqlClientResponseToReason: UrqlClient.urqlClientResponseToReason,
  executeQuery: UrqlClient.executeQuery,
  executeMutation: UrqlClient.executeMutation,
  executeSubscription: UrqlClient.executeSubscription,
  createRequestOperation: UrqlClient.createRequestOperation
};

var Hooks = {
  useMutation: UrqlUseMutation.useMutation,
  useDynamicMutation: UrqlUseMutation.useDynamicMutation,
  useQuery: UrqlUseQuery.useQuery,
  useSubscription: UrqlUseSubscription.useSubscription
};

var UrqlTypes = 0;

var Context = 0;

var Provider = 0;

var Consumer = 0;

var Query = 0;

var Mutation = 0;

var Subscription = 0;

var SubscriptionWithHandler = 0;

var $$Request = 0;

var CombinedError = 0;

var Exchanges = 0;

export {
  UrqlTypes ,
  Client ,
  Context ,
  Provider ,
  Consumer ,
  Query ,
  Mutation ,
  Subscription ,
  SubscriptionWithHandler ,
  $$Request ,
  CombinedError ,
  Exchanges ,
  Hooks ,
  
}
/* UrqlClient Not a pure module */
