// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Css from "bs-css/src/Css.js";

var container = Css.style(/* :: */[
      Css.position(Css.absolute),
      /* :: */[
        Css.display(Css.grid),
        /* :: */[
          Css.gridTemplateColumns(/* :: */[
                Css.rem(15),
                /* :: */[
                  /* `fr */[
                    22860,
                    1
                  ],
                  /* [] */0
                ]
              ]),
          /* :: */[
            Css.height(Css.pct(100)),
            /* :: */[
              Css.width(Css.pct(100)),
              /* :: */[
                Css.fontFamily("Roboto"),
                /* [] */0
              ]
            ]
          ]
        ]
      ]
    ]);

var list = Css.style(/* :: */[
      Css.paddingLeft(Css.rem(0)),
      /* :: */[
        Css.margin(Css.rem(-0.5)),
        /* :: */[
          Css.overflow(Css.auto),
          /* [] */0
        ]
      ]
    ]);

var listItem = Css.style(/* :: */[
      Css.listStyleType(/* none */-922086728),
      /* :: */[
        Css.padding3(Css.rem(0.5), Css.rem(0), Css.rem(0.5)),
        /* :: */[
          Css.hover(/* :: */[
                Css.backgroundColor(Css.hex("F29441")),
                /* [] */0
              ]),
          /* :: */[
            Css.cursor(/* pointer */-786317123),
            /* [] */0
          ]
        ]
      ]
    ]);

var button = Css.style(/* :: */[
      Css.color(Css.hex("ffff")),
      /* :: */[
        Css.backgroundColor(Css.transparent),
        /* :: */[
          Css.borderColor(Css.transparent),
          /* :: */[
            Css.fontSize(Css.rem(1)),
            /* :: */[
              Css.cursor(/* pointer */-786317123),
              /* :: */[
                Css.width(Css.pct(100)),
                /* :: */[
                  Css.textAlign(/* left */-944764921),
                  /* [] */0
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var dexTitle = Css.style(/* :: */[
      Css.fontSize(Css.rem(2)),
      /* :: */[
        Css.margin(Css.zero),
        /* :: */[
          Css.padding(Css.rem(0.5)),
          /* [] */0
        ]
      ]
    ]);

var dexText = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.backgroundColor(Css.white),
          /* :: */[
            Css.width(Css.pct(100)),
            /* :: */[
              Css.borderBottomLeftRadius(Css.pct(5.0)),
              /* :: */[
                Css.borderBottomRightRadius(Css.pct(5.0)),
                /* :: */[
                  Css.borderTop(Css.px(2), Css.solid, Css.hsl(Css.deg(210), 23, 95)),
                  /* :: */[
                    Css.alignItems(Css.center),
                    /* [] */0
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var dex = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.flexDirection(Css.column),
        /* :: */[
          Css.width(Css.pct(100)),
          /* :: */[
            Css.borderRadius(Css.pct(5)),
            /* :: */[
              Css.background(Css.linearGradient(Css.deg(45), /* :: */[
                        /* tuple */[
                          Css.zero,
                          Css.hex("F29441")
                        ],
                        /* :: */[
                          /* tuple */[
                            Css.pct(100),
                            Css.hex("A04AD9")
                          ],
                          /* [] */0
                        ]
                      ])),
              /* :: */[
                Css.border(Css.px(2), Css.solid, Css.hsl(Css.deg(210), 23, 95)),
                /* :: */[
                  Css.overflow(Css.hidden),
                  /* :: */[
                    Css.alignItems(Css.center),
                    /* :: */[
                      Css.boxShadow(Css.Shadow.box(Css.px(0), Css.px(0), Css.px(6), undefined, undefined, Css.hsl(Css.deg(0), 0, 80))),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ]
          ]
        ]
      ]
    ]);

var dexContainer = Css.style(/* :: */[
      Css.display(Css.flexBox),
      /* :: */[
        Css.alignItems(Css.flexStart),
        /* :: */[
          Css.justifyContent(Css.center),
          /* :: */[
            Css.margin(Css.auto),
            /* :: */[
              Css.width(Css.rem(25)),
              /* [] */0
            ]
          ]
        ]
      ]
    ]);

export {
  container ,
  list ,
  listItem ,
  button ,
  dexTitle ,
  dexText ,
  dex ,
  dexContainer ,
  
}
/* container Not a pure module */
